[package]
name = "pmem_cell"
version = "0.1.0"
authors = ["刘丰源 <liufy17@mails.tsinghua.edu.cn>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lazy_static = "1.4.0"
spin = "0.5"
